/**
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CrearUnMensajeRequest
 */
class CrearUnMensajeRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.leido = this.constructor.getValue(obj.leido);
        this.borrado = this.constructor.getValue(obj.borrado);
        this.data = this.constructor.getValue(obj.data);
        this.expireAt = this.constructor.getValue(obj.expireAt);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'leido', realName: 'leido' },
            { name: 'borrado', realName: 'borrado' },
            { name: 'data', realName: 'data', type: 'Data14' },
            { name: 'expireAt', realName: 'expireAt' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CrearUnMensajeRequest;
