/**
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of ModificarUnGrupoPorNombreRequest
 */
class ModificarUnGrupoPorNombreRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.nombre = this.constructor.getValue(obj.nombre);
        this.aplicacion = this.constructor.getValue(obj.aplicacion);
        this.usuarios = this.constructor.getValue(obj.usuarios);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'nombre', realName: 'nombre' },
            { name: 'aplicacion', realName: 'aplicacion' },
            { name: 'usuarios', realName: 'usuarios', array: true },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = ModificarUnGrupoPorNombreRequest;
