/**
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const CrearUnMensajeAlGrupoPorNombreRequest =
  require('../lib/Models/CrearUnMensajeAlGrupoPorNombreRequest');
const CrearUnMensajeAlGrupoRequest = require('../lib/Models/CrearUnMensajeAlGrupoRequest');
const ModificarUnGrupoPorNombreRequest = require('../lib/Models/ModificarUnGrupoPorNombreRequest');
const CrearUnMensajeAlGrupoPorNombreResponse =
  require('../lib/Models/CrearUnMensajeAlGrupoPorNombreResponse');
const ModificarUnGrupoRequest = require('../lib/Models/ModificarUnGrupoRequest');
const CrearUnMensajeAlGrupoResponse = require('../lib/Models/CrearUnMensajeAlGrupoResponse');
const ModificarUnGrupoPorNombreResponse =
  require('../lib/Models/ModificarUnGrupoPorNombreResponse');
const ModificarUnGrupoResponse = require('../lib/Models/ModificarUnGrupoResponse');
const CrearUnGrupoRequest = require('../lib/Models/CrearUnGrupoRequest');
const LeerGruposDeUnaAplicacionResponse =
  require('../lib/Models/LeerGruposDeUnaAplicacionResponse');
const CrearUnGrupoResponse = require('../lib/Models/CrearUnGrupoResponse');
const LeerGruposResponse = require('../lib/Models/LeerGruposResponse');
const LeerUnGrupoPorNombreResponse = require('../lib/Models/LeerUnGrupoPorNombreResponse');
const LeerUnGrupoResponse = require('../lib/Models/LeerUnGrupoResponse');
const CrearUnMensajeRequest = require('../lib/Models/CrearUnMensajeRequest');
const ModificarUnMensajeLeidoBorradoResponse =
  require('../lib/Models/ModificarUnMensajeLeidoBorradoResponse');
const ModificarUnMensajeLeidoBorradoRequest =
  require('../lib/Models/ModificarUnMensajeLeidoBorradoRequest');
const LeerMensajesResponse = require('../lib/Models/LeerMensajesResponse');
const Data5 = require('../lib/Models/Data5');
const CrearUnMensajeResponse = require('../lib/Models/CrearUnMensajeResponse');
const Data14 = require('../lib/Models/Data14');
const LeerUnMensajeResponse = require('../lib/Models/LeerUnMensajeResponse');
const Data6 = require('../lib/Models/Data6');
const CrearUnMensajeAAplicaciNResponse = require('../lib/Models/CrearUnMensajeAAplicaciNResponse');
const CrearUnMensajeAAplicaciNRequest = require('../lib/Models/CrearUnMensajeAAplicaciNRequest');
const Data = require('../lib/Models/Data');
const Datum = require('../lib/Models/Datum');
const LeerAplicacionesResponse = require('../lib/Models/LeerAplicacionesResponse');

const classMap = {
    CrearUnMensajeAlGrupoPorNombreRequest,
    CrearUnMensajeAlGrupoRequest,
    ModificarUnGrupoPorNombreRequest,
    CrearUnMensajeAlGrupoPorNombreResponse,
    ModificarUnGrupoRequest,
    CrearUnMensajeAlGrupoResponse,
    ModificarUnGrupoPorNombreResponse,
    ModificarUnGrupoResponse,
    CrearUnGrupoRequest,
    LeerGruposDeUnaAplicacionResponse,
    CrearUnGrupoResponse,
    LeerGruposResponse,
    LeerUnGrupoPorNombreResponse,
    LeerUnGrupoResponse,
    CrearUnMensajeRequest,
    ModificarUnMensajeLeidoBorradoResponse,
    ModificarUnMensajeLeidoBorradoRequest,
    LeerMensajesResponse,
    Data5,
    CrearUnMensajeResponse,
    Data14,
    LeerUnMensajeResponse,
    Data6,
    CrearUnMensajeAAplicaciNResponse,
    CrearUnMensajeAAplicaciNRequest,
    Data,
    Datum,
    LeerAplicacionesResponse,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
